image: mono:latest

stages:
  - build
  - test
  - deploy

before_script:
  - nuget restore "home_work_2/home_work_2.sln" -NonInteractive
  - nuget restore "home_work_3/home_work_3.sln" -NonInteractive
  - nuget restore "home_work_4/home_work_4.sln" -NonInteractive

#### HOME WORK 3 AREA ####

release_hw2:
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - build/release/TestApplication.exe
  script:
    # The output path is relative to the position of the csproj-file
    - msbuild /p:Configuration="Release" /p:Platform="Any CPU"
      /p:OutputPath="./../../build/release/" "home_work_2/home_work_2.sln"

debug_hw2:
  stage: test
  script:
    # The output path is relative to the position of the csproj-file
    - msbuild /p:Configuration="Debug" /p:Platform="Any CPU"
      /p:OutputPath="./../../build/debug/" "home_work_2/home_work_2.sln"
    - mono home_work_2/packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe PlayerLibNUnitTest/build/debug/PlayerLibNUnitTest.dll

#### HOME WORK 3 AREA ####
release_hw3:
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - build/release/home_work_3.exe
  script:
    # The output path is relative to the position of the csproj-file
    - msbuild /p:Configuration="Release" /p:Platform="Any CPU"
      /p:OutputPath="./../../build/release/" "home_work_3/home_work_3.sln"

debug_hw3:
  stage: test
  script:
    # The output path is relative to the position of the csproj-file
    - msbuild /p:Configuration="Debug" /p:Platform="Any CPU"
      /p:OutputPath="./../../build/debug/" "home_work_3/home_work_3.sln"
#    - mono packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe build/debug/MyProject.Test.dll
